substitutions:
  name: "alarm-clock"
  friendly_name: "Alarm Clock"

blob:
#  - id: the_file
#    file: "audio/abracadabra.mp3"
#  - id: the_file
#    file: "audio/billy_jean-0.mid"
  - id: the_file
    file: "audio/I_can_see_for_miles.mid"
#  - id: the_file
#    file: "audio/dragon_mono.wav"
#  - id: the_file
#    file: "audio/arcade.mp3"
#  - id: the_file
#    file: "audio/bike_horn.wav"


esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG
  logs:
    sensor: INFO
    apds9960: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  manual_ip:
    static_ip: !secret net_alarm_clock_ip
    gateway: !secret net_gateway
    subnet: !secret net_mask
    dns1: !secret net_dns
    dns2: 9.9.9.9

ota:
  password: !secret alarm_clock_ota_password

api:
  password: !secret api_password
  # Don't reboot the device when no API client is connected. This makes it
  # feasible to use the device independent from Home Assistant.
  reboot_timeout: 0s

external_components:
  - source:
      type: local
      path: esphome-vs10xx/components

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

vs10xx:
  id: audio_decoder
  type: vs1003
  reset_pin: GPIO12
  xcs_pin: GPIO32
  xdcs_pin: GPIO33
  dreq_pin: GPIO15
  plugins:
    - wavfix
    - dacmono

sensor:
  # This sensor represents the rotary function of the rotary encoder.
  - platform: rotary_encoder
    id: rotary_encoder_pos
    entity_category: diagnostic
    pin_a:
      number: GPIO26
      mode: INPUT_PULLUP
    pin_b:
      number: GPIO27
      mode: INPUT_PULLUP
    resolution: 1
    on_clockwise:
      then:
        - vs10xx.volume_up:
            delta: 5%
    on_anticlockwise:
      then:
        - vs10xx.volume_down: 5%

binary_sensor:
  # This binary sensor represents the key function of the rotary encoder.
  - platform: gpio
    id: rotary_encoder_key
    entity_category: diagnostic
    pin:
      number: GPIO25
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - vs10xx.play: 
            blob_id: the_file
        #- vs10xx.set_volume: 85%
